#!/usr/bin/env python3
"""AIDOCS crown-gate - REPORT-FIRST static-analysis + dev-loop recon runner.

Runs each guardian lane in REPORT mode, writes a classified artifact per lane to
scratch/reports/, and prints a summary. It NEVER blocks (always exits 0) — it is
reconnaissance, not a gate. The ONLY blocking gate is Ruff, enforced separately
in CI (.github/workflows/pr-ci.yml) and pre-commit. New guardians graduate from
this report-first runner to blocking only after proven low false positives (see
scratch/CROWN_GATE_DOCTRINE.md).

Lanes (all optional except ruff/clones; absent ones degrade honestly):
  ruff          correctness/style   (also the live blocking gate)
  basedpyright  type-risk           (baseline mode; report-only)
  semgrep       security-law        (core/semgrep/aidocs-laws.yml; CI/Linux lane)
  vulture       dead-code           (project-wide; optional)
  clones        duplicate/slop      (built-in AST; no dependency)
  jscpd         duplicate/slop      (npx; optional cross-language)
  durations     performance-loop    (pytest --durations; --profile only)

Usage:
  python core/scripts/crown_gate.py            # fast static lanes
  python core/scripts/crown_gate.py --profile  # + suite durations (slow)
  python core/scripts/crown_gate.py --lane semgrep
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = "mcp/server/aidocs_mcp"
REPORTS = ROOT / "scratch" / "reports"

CLASS = {
    "ruff": "correctness/style", "basedpyright": "type-risk",
    "semgrep": "security-law", "vulture": "dead-code",
    "clones": "duplicate/slop", "jscpd": "duplicate/slop",
    "durations": "performance-loop",
}


def _run(argv, timeout=600):
    try:
        p = subprocess.run(argv, capture_output=True, text=True, cwd=str(ROOT),
                           timeout=timeout)
        return p.returncode, p.stdout or "", p.stderr or ""
    except FileNotFoundError as exc:
        return 127, "", f"not found: {exc}"
    except subprocess.TimeoutExpired:
        return 124, "", "timeout"


def _write(name, payload):
    REPORTS.mkdir(parents=True, exist_ok=True)
    (REPORTS / f"{name}.json").write_text(
        json.dumps(payload, indent=2, default=str), "utf-8")


def _write_summary_md(summary):
    """Durable, human-reviewable summary so reports are never just lost JSON."""
    lines = ["# AIDOCS crown-gate report (report-first; Ruff is the only "
             "blocking gate)", "",
             "Generated by `core/scripts/crown_gate.py`. Non-blocking.", "",
             "| lane | class | status | key result |", "|---|---|---|---|"]
    for name, res in summary.items():
        avail = res.get("available")
        status = ("ok" if avail is True
                  else "via-npx" if avail == "via npx" else "unavailable/degraded")
        key = {k: v for k, v in res.items()
               if k in ("findings", "errors", "warnings", "files_analyzed",
                        "clusters", "clones", "total", "actionable", "note",
                        "reason", "needs", "blocking_gate")}
        lines.append(f"| {name} | {res.get('class')} | {status} | "
                     f"{str(key)[:160]} |")
    (REPORTS / "SUMMARY.md").write_text("\n".join(lines) + "\n", "utf-8")


def lane_ruff():
    code, out, _ = _run([sys.executable, "-m", "ruff", "check", SRC,
                         "--output-format", "json"])
    findings = json.loads(out) if out.strip().startswith("[") else []
    return {"available": True, "blocking_gate": True, "findings": len(findings),
            "note": "this lane is ALSO the live blocking gate (CI/pre-commit)"}


def lane_basedpyright():
    if (shutil.which("basedpyright") is None
            and importlib.util.find_spec("basedpyright") is None):
        return {"available": False, "needs": "pip install basedpyright"}
    # --project anchors the [tool.basedpyright] config in mcp/ so its (config-dir-
    # relative) include = the law-critical modules. Without it, basedpyright
    # ignores the config and scans the whole repo (~1100 files) — the scope bug.
    code, out, _ = _run([sys.executable, "-m", "basedpyright", "--project",
                         "mcp/pyproject.toml", "--outputjson"], timeout=400)
    try:
        data = json.loads(out)
        summ = data.get("summary", {})
        return {"available": True, "report_only": True,
                "errors": summ.get("errorCount"), "warnings": summ.get("warningCount"),
                "files_analyzed": summ.get("filesAnalyzed"),
                "scope": "law-critical modules ([tool.basedpyright] include)"}
    except Exception:
        return {"available": True, "report_only": True, "note": "ran; non-JSON"}


def lane_semgrep():
    import importlib.util as u
    if u.find_spec("semgrep") is None and shutil.which("semgrep") is None:
        return {"available": False, "needs": "pip install semgrep (CI/Linux)"}
    code, out, _ = _run([sys.executable, "-m", "semgrep", "scan", "--config",
                         "core/semgrep/aidocs-laws.yml", SRC, "--metrics=off",
                         "--json"], timeout=300)
    if code not in (0, 1) or not out.strip():
        return {"available": False, "report_only": True,
                "note": f"engine not runnable here (exit {code}); CI/Linux lane"}
    data = json.loads(out)
    return {"available": True, "report_only": True,
            "findings": len(data.get("results", []))}


def lane_clones():
    sys.path.insert(0, str(ROOT / "mcp" / "server"))
    from aidocs_mcp import slop_backends as sb
    files = []
    for p in (ROOT / SRC).rglob("*.py"):
        try:
            files.append((str(p.relative_to(ROOT)), p.read_text("utf-8")))
        except Exception:
            continue
    r = sb.ast_clones(files, min_nodes=40, min_occurrences=2)
    return {"available": True, "report_only": True,
            "clusters": r["total_clusters"], "source": "aidocs_ast_clone"}


def lane_vulture():
    import importlib.util as u
    if u.find_spec("vulture") is None:
        return {"available": False, "needs": "pip install vulture"}
    sys.path.insert(0, str(ROOT / "mcp" / "server"))
    from aidocs_mcp import slop_backends as sb
    r = sb.run_vulture([SRC])
    return {"available": True, "report_only": True,
            "findings": r.get("total"), "note": "classify, never auto-delete"}


def lane_jscpd():
    exe = shutil.which("jscpd")
    if exe is None and shutil.which("npx") is None:
        return {"available": False, "needs": "npm i -g jscpd (or npx)"}
    # Actually RUN jscpd (don't claim availability without producing a result).
    outdir = REPORTS / "jscpd"
    base = [exe] if exe else ["npx", "--yes", "jscpd"]
    code, _out, _err = _run(base + [SRC, "--reporters", "json", "--output",
                                    str(outdir), "--silent"], timeout=180)
    rep = outdir / "jscpd-report.json"
    if code != 0 or not rep.is_file():
        return {"available": False, "report_only": True,
                "note": f"jscpd NOT executed (exit {code}); needs `npm i -g jscpd` "
                        "or network for npx - degraded, not clean"}
    try:
        d = json.loads(rep.read_text("utf-8"))
        clones = (d.get("statistics", {}).get("total", {}) or {}).get("clones")
        return {"available": True, "report_only": True, "clones": clones,
                "source": "jscpd"}
    except Exception:
        return {"available": True, "report_only": True, "note": "ran; report unparsed"}


def lane_durations():
    import re
    code, out, err = _run([sys.executable, "-m", "pytest", "mcp/tests/security",
                           "-q", "--durations=25", "-p", "no:cacheprovider"],
                          timeout=1200)
    # pytest exits: 0 pass, 1 failures, 5 no-tests. Anything else = the run
    # broke → durations are NOT trustworthy; report degraded, not "no slow tests".
    if code not in (0, 1, 5):
        return {"available": False, "report_only": True,
                "note": f"pytest run failed (exit {code}); durations not collected"}
    pat = re.compile(r"^([\d.]+)s\s+(call|setup|teardown)\s+(.+)$")
    rows = []
    for ln in (out + err).splitlines():
        m = pat.match(ln.strip())
        if m:
            rows.append({"seconds": float(m.group(1)), "phase": m.group(2),
                         "test": m.group(3)})
    rows.sort(key=lambda r: r["seconds"], reverse=True)
    return {"available": True, "report_only": True, "exit": code,
            "scope": "mcp/tests/security (sample slice)",
            "slowest": rows[:25],
            "actionable": [r["test"] for r in rows[:5]],
            "note": "full suite: pytest mcp/tests --durations=50"}


LANES = {
    "ruff": lane_ruff, "basedpyright": lane_basedpyright, "semgrep": lane_semgrep,
    "clones": lane_clones, "vulture": lane_vulture, "jscpd": lane_jscpd,
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", action="store_true", help="run suite durations (slow)")
    ap.add_argument("--lane", help="run a single lane")
    args = ap.parse_args()
    lanes = dict(LANES)
    if args.profile:
        lanes["durations"] = lane_durations
    if args.lane:
        lanes = {args.lane: lanes[args.lane]} if args.lane in lanes else {}
        if not lanes:
            print(f"unknown lane; choose from {list(LANES)} + durations")
            return 0
    print("AIDOCS crown-gate - REPORT-FIRST (non-blocking; Ruff is the live gate)\n")
    summary = {}
    for name, fn in lanes.items():
        t = time.perf_counter()
        try:
            res = fn()
        except Exception as exc:  # noqa: BLE001
            res = {"available": False, "error": repr(exc)}
        res["class"] = CLASS.get(name, "?")
        res["seconds"] = round(time.perf_counter() - t, 1)
        _write(name, res)
        summary[name] = res
        avail = res.get("available")
        mark = "ok " if avail is True else ("via" if avail == "via npx" else "-- ")
        print(f"  [{mark}] {name:<13} {res['class']:<18} "
              f"{ {k: v for k, v in res.items() if k not in ('class',)} }")
    _write("_summary", summary)
    _write_summary_md(summary)
    print(f"\nartifacts -> {REPORTS}  (SUMMARY.md + per-lane .json)")
    return 0   # report-first: NEVER blocks


if __name__ == "__main__":
    raise SystemExit(main())
